### ISSUE TITLE
pod install can not find UXSDK-beta 0.4

### ISSUE THREAD

**Issue by apdofficial** [dji-sdk/Mobile-UXSDK-Beta-iOS#17]
Podfile:
![image](https://user-images.githubusercontent.com/43278252/102880751-1e362400-444c-11eb-9dea-b7e4b65f5eb0.png)

<img width="692" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/43278252/102880648-f47cfd00-444b-11eb-9125-e7f3108b2279.png">

**Comment by dji-lisafedane** [comment]
@apdofficial -  I wish I had a prize for how quickly you started working on this release version!  Thank you for reporting this and we're shooting to have a fix in about 48 hours but hopefully sooner.

**Comment by alainpimentel** [comment]
Pod install is working now
