### ISSUE TITLE
Error during upload app with Beta SDK to AppStore

### ISSUE THREAD

**Issue by nab0y4enko** [dji-sdk/Mobile-UXSDK-Beta-iOS#22]
We cannot transfer our for testing to pilots in TestFlight, because the validator finds the wrong value for CFBundleShortVersionString

> Summary:
 

> 1 package(s) were not uploaded because they had problems:
> 	/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/6C703A03-7FDA-4D6C-8219-A62738692D52/1196876612.itmsp - Error Messages:
> 		ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '4.14-trial1' in the Info.plist file at '${bundlePath}' must be a period-separated list of at most three non-negative integers. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring"
> 2020-12-23 22:32:39.867 altool[21700:69781] *** Error: Error uploading '/Users/vagrant/deploy/DroneUpApp.ipa'.
> 2020-12-23 22:32:39.867 altool[21700:69781] *** Error: code -18000 (ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '4.14-trial1' in the Info.plist file at '${bundlePath}' must be a period-separated list of at most three non-negative integers. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring")
> Uploading IPA failed: exit status 1

**Comment by dji-lisafedane** [comment]
Thanks reporting this bug and fortunately it's a known issue with a fix on the way.  In the meanwhile, there is a confirmed work-a-round: 

**Fix the short version string in the MSDK framework**

![image](https://user-images.githubusercontent.com/39347132/103042540-d805c100-452e-11eb-9d21-acc9ec97616c.png)

**Comment by nab0y4enko** [comment]
Thanks. Will wait updated version

**Comment by nab0y4enko** [comment]
Have been fixed and tested. Thanks
