### ISSUE TITLE
Default layout

### ISSUE THREAD

**Issue by DesmanLead** [dji-sdk/Mobile-UXSDK-Beta-iOS#3]
Is there a plan to implement something similar to DUXDefaultLayoutViewController based on new SDK? Is there some kind of roadmap available?

**Comment by dji-lisafedane** [comment]
Yes, the UX team does plan on releasing a Default Layout in a 2020 release - we are targeting the next 2 to 3 months.

**Comment by alainpimentel** [comment]
@DesmanLead although we don't have a DefaultLayout as part of the UX SDK framework, you can see an example in our sample. https://github.com/dji-sdk/Mobile-UXSDK-Beta-iOS/blob/master/UXSDKBetaSample/UXSDKBetaSample/DefaultLayoutViewController.swift
We will continue to populate it with more widgets and panels in future releases.

**Comment by BillMalkin** [comment]
That link is broken. So too is a link in the page at https://github.com/dji-sdk/Mobile-UXSDK-Beta-iOS, where it says _Check out our sample app to get started._  The link is https://github.com/dji-sdk/Open-Source-UXSDK-iOS/UXSDKBetaSample

**Comment by dji-lisafedane** [comment]
@BillMalkin Thanks for letting us know!

**Comment by dji-lisafedane** [comment]
I believe Alain was trying to link you here: https://github.com/dji-sdk/Mobile-UXSDK-Beta-iOS/blob/master/UXSDKBetaSampleApp/UXSDKBetaSampleApp/SampleFeatures/DefaultLayoutViewController.swift

**Comment by BillMalkin** [comment]
Thanks @dji-lisafedane!
