### ISSUE TITLE
Update dependency to support DJI-SDK-iOS 4.11.1

### ISSUE THREAD

**Issue by a2hill** [dji-sdk/Mobile-UXSDK-Beta-iOS#4]
Currently when installing `DJI-UXSDK-iOS-Beta` via cocoapods it depends on `DJI-SDK-iOS` 4.11. This means that projects which attempt to update to `DJI-SDK-iOS` 4.11.1 fail with the following error:

```
[!] CocoaPods could not find compatible versions for pod "DJI-SDK-iOS":
  In Podfile:
    DJI-SDK-iOS (= 4.11.1)

    DJI-UXSDK-iOS-Beta (~> 0.1.1) was resolved to 0.1.1, which depends on
      DJI-UXSDK-iOS-Beta-Core (= 0.1.1) was resolved to 0.1.1, which depends on
        DJI-SDK-iOS (= 4.11)
```

Will there be an update to this before the main release or should we plan on having to work around this in the mean time?

**Comment by dji-lisafedane** [comment]
Thank you for bringing this to our attention, DJI Developer Support is researching the issue with the iOS UX team.  I'll give you an update here as soon as possible.
